### ISSUE TITLE
Sending To a specific device or devices call are not working

### ISSUE THREAD

**Issue by pu2clr** [nluo/pushwoosh-node-client#12]
I have tried to send message to specific device by using one of these tow methods:  
// Push to a device
client.sendMessage('Hello world', 'device token', function(error, response) {
});
// Push to multiple devices
client.sendMessage('Hello world', ['deviceToken1', 'deivceToken2'], function(error, response) {
});

But these two methods are broadcasting to all devices. I mean, they are sending message to all devices linked to my Cordova App. 

Here is my test: 
var Pushwoosh = require('pushwoosh-client');
var client = new Pushwoosh("My AppCode", "My AuthToken");

// I Got my Device tokens by using pushNotification.getPushwooshHWID( function (token) { ...} 
// on  my Cordova device App.
// Token exemples: 
// My iPhone 6........: 0547991D-DF03-4093-906F-66B6B5731A54
// My Iphone 5........: F5E66FE0-1179-4A43-9AD1-CE2F12C01EA0
// My Windows Phone...: 6A56CA4E7993F5177E373CF038CEE58AA5C9185A
// My Android.........: ce85d0e6a54e835d

router.post('/:comando', function (req, res) {
    var comando = req.params.comando;
    console.log('Remote API Teste - Push Notificatio - ' + comando); // Single or Multiple
    if (comando === 'single') { // to single Device
        var device = '6A56CA4E7993F5177E373CF038CEE58AA5C9185A';
        console.log('Trying to send  Push notification to ' + device);
        client.sendMessage('Just one device should receive this message!', device, function (error, response) {
            if (error) {
                console.log('Error: ' + JSON.stringify(error));
                return;
            }
            console.log('Push notification was sent to ' + device);
        });
    } else { // to multiple devices
        var devices = ['6A56CA4E7993F5177E373CF038CEE58AA5C9185A', 'F5E66FE0-1179-4A43-9AD1-CE2F12C01EA0'];
        devices.forEach(function (device) {
            console.log('Trying to send  Push notification to ' + device);
        });
        client.sendMessage('Two devices should receive this message!', devices, function (error, response) {
            if (error) {
                console.log('Error: ' + JSON.stringify(error));
                return;
            }
            devices.forEach(function (device) {
                console.log('Push notification was sent to ' + device);
            });
        });
    }
    res.send(null);
});

-----
Console output: 

Single: 
www-1 Remote API Teste - Push Notificatio - single
www-1 Trying to send  Push notification to 6A56CA4E7993F5177E373CF038CEE58AA5C9185A
www-1 POST /users/single 200 15.527 ms - 0

Multiple: 
www-1 Remote API Teste - Push Notificatio - multiple
www-1 Trying to send  Push notification to 6A56CA4E7993F5177E373CF038CEE58AA5C9185A
Trying to send  Push notification to F5E66FE0-1179-4A43-9AD1-CE2F12C01EA0
www-1 POST /users/multiple 200 63.967 ms - 0
www-1 Push notification was sent to 6A56CA4E7993F5177E373CF038CEE58AA5C9185A
www-1 Push notification was sent to F5E66FE0-1179-4A43-9AD1-CE2F12C01EA0

In any situation, the code above are send push to all devices linked to my Cordova App (Android, Ios and Windows Phone).

**Comment by nluo** [comment]
@pu2clr Thanks for reporting the issue. I will investigate the issue

**Comment by nluo** [comment]
@pu2clr : I have fixed the bug in the recent pull request https://github.com/nluo/pushwoosh-node-client/pull/13 and published the latest version: 1.3.1. Could you upgrade and see if it fixes for you? Thanks
