### ISSUE TITLE
Specify custom sound file with sendMessage call.

### ISSUE THREAD

**Issue by MaartenWeber** [nluo/pushwoosh-node-client#17]
Hi, 

I've been using your nodejs client and I really like it, keep up the good work :). I do like to know if it's possible to specify a sound file that needs to be played whenever a notification arrives. I though it might be through options, but I don't think that's the case. If so, please let me know. And if it's not possible (yet), please add it to the feature list for the future :).

Thanks in advance!

Kinds regards,

Maarten

**Comment by baldercm** [comment]
Hi Maarten,

yes, you should be able to pass any valid PushWoosh configuration using the `options` hash. I haven't tested sound options myself, though, but something like this should work:
```javascript
const Pushwoosh = require('pushwoosh-client')
const client    = new Pushwoosh("AppCode", "AuthToken")

let options = {
  ios_sound: 'sound file.wav',
  android_sound: 'soundfile',
  devices: ['deviceToken1', 'deviceToken2', 'deviceToken3']
}
client.sendMessage('Hello world', options, function(error, response) {
  // ...
})
```

**Comment by MaartenWeber** [comment]
Ah, I'll give it shot then and let you know if I can get it to work :)

Thanks for your reply!

**Comment by nluo** [comment]
@MaartenWeber Yes please try that into options (pls see http://docs.pushwoosh.com/docs/createmessage and search for sound) as per @baldercm said. Thanks for your kind words and happy it could help you :)

@baldercm Thanks for your reply :+1:

**Comment by nluo** [comment]
@MaartenWeber Have you tried out and see if it works for you? If it works we could close this issue :)

**Comment by MaartenWeber** [comment]
Oh yeah, forgot to reply :) Sorry. It worked, so it can be closed :)

**Comment by nluo** [comment]
@MaartenWeber Great it works for you! I will close this issue now
