### ISSUE TITLE
Dangerous default to "all devices"

### ISSUE THREAD

**Issue by brabster** [nluo/pushwoosh-node-client#19]
Hi there,

I just accidentally broadcast thousands of erroneous messages to my app's users because (I think) I failed to unwrap a device ID value from an object in my sendMessage call, so the device ID ended up null.

That seems very dangerous to me and I think extra checks in the device ID logic (like if the device ID isn't `undefined`, `null` on top of the current checks, blow up - mine would have been an object) and/or a sendMessageNeverBroadcast or some variant function for usecases like mine when I want to be super-explicit if I actually want a broadcast message.

Alternatively, we could add a config option to disable broadcast or something like that.

Happy to get busy PRing, but didn't want to waste my time if these suggestions aren't appropriate for this library?

**Comment by nluo** [comment]
@brabster That's a good suggestion, I will have a look

**Comment by nluo** [comment]
@brabster I have merged my PR which you could now configure to not send to all devices. And will give you callback error without sending push notifications if you don't pass the device param.

**Comment by nluo** [comment]
@brabster Could you have a look if it works for you?

**Comment by brabster** [comment]
LGTM. I'll see if I can test it against a real pushwoosh app tomorrow but that looks like just what I was looking for. Thanks!
