### ISSUE TITLE
Sending multiple specific device pushes

### ISSUE THREAD

**Issue by Wasiq08** [nluo/pushwoosh-node-client#8]
I am using push-client node npm for server side.It does not allow to send pushes to specific devices instead it broadcast to all subscribers.

**Comment by baldercm** [comment]
Hi @Wasiq08 We are using this library for sending pushes to specific devices and it's working properly. Perhaps if you could give some more details we can find the issue.

**Comment by nluo** [comment]
@Wasiq08 : Do you still have the issue? If you still have and like Baldercm said could you give us more details e.g. your payload so we can help you?

Otherwise I will close this issue.

**Comment by nluo** [comment]
@Wasiq08  I have fixed the bug in the recent pull request #13 and published the latest version: 1.3.1. Could you upgrade and see if it fixes for you? Thanks

**Comment by nluo** [comment]
@Wasiq08  I have fixed the bug in the recent pull request #13 and published the latest version: 1.3.1. This should fix the issue/bug you have reported: sending push message to multiple specific devices

**Comment by nluo** [comment]
@Wasiq08 : Thanks for letting me know the issue resloved!
